name: BMO MLOps Example
description: "Demonstrates a number of concepts including web scraping, vector databases, model deployment, model usage, Langchain, application building, and instruction following/tuning."
author: "Cloudera"
date: "2024-06-21"
specification_version: 1.0
prototype_version: 1.0

environment_variables:
  DATABASE:
    default: ""
    description: "Database to use for the data. It is created if it does not exist."
  CONNECTION_NAME:
    default: "go01-aw-dl"
    description: "Default connection name to DL"
  STORAGE:
    default: "s3a://go01-demo"
    description: "Object storage path"

runtimes:
  - editor: Workbench
    kernel: Python 3.10
    edition: Standard
    addons: ["Spark 3.2.3 - CDE 1.20.3 - HOTFIX-2"]
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU
    addons: ["Spark 3.2.3 - CDE 1.20.3 - HOTFIX-2"]
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Standard
    addons: ["Spark 3.2.3 - CDE 1.20.3 - HOTFIX-2"]

tasks:
  - type: run_session
    name: Install dependencies
    script: 00_install_requirements.py
    short_summary: Install dependencies
    kernel: python3
    cpu: 2
    memory: 4

  - type: create_job
    name: Generate data
    entity_label: generate_data
    script: 00_datagen.py
    arguments: None
    short_summary: Create job - generate fake data
    cpu: 2
    memory: 4

  - type: create_job
    name: Pull git
    entity_label: pull_git
    cpu: 0.5
    memory: 0.5
    script: cml/pull_git.py
    arguments: None
    short_summary: Create job - git pull
