name: BMO MLOps Example
description: "Demonstrates a number of concepts including web scraping, vector databases, model deployment, model usage, Langchain, application building, and instruction following/tuning."
author: "Cloudera"
date: "2024-06-21"
specification_version: 1.0
prototype_version: 1.0

runtimes:
  - editor: Workbench
    kernel: Python 3.10
    edition: Standard
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU
  - editor: Workbench
    kernel: Python 3.10
    edition: Nvidia GPU
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Standard

tasks:
  - type: run_session
    name: Install dependencies
    script: 00_install_prerequisites.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 4

  - type: create_job
    name: Generate data
    entity_label: generate_data
    script: 00_datagen.py
    arguments: None
    short_summary: Create job to generate fake data.
    cpu: 2
    memory: 4
