name: BMO MLOps Example
description: "Demonstrates a number of concepts including web scraping, vector databases, model deployment, model usage, Langchain, application building, and instruction following/tuning."
author: "Cloudera"
date: "2024-06-21"
specification_version: 1.0
prototype_version: 1.0

environment_variables:
  DATABASE:
    default: ""
    description: "Database to use for the data. It is created if it does not exist."
  CONNECTION_NAME:
    default: "go01-aw-dl"
    description: "Default connection name to DL"
  STORAGE:
    default: "s3a://go01-demo"
    description: "Object storage path"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard
    addons: ["Spark 3.3.0 - CDE 1.20.3 - HOTFIX-2"]
    version: "2024.02"
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Standard
    addons: ["Spark 3.3.0 - CDE 1.20.3 - HOTFIX-2"]

tasks:
  - type: run_session
    name: Install dependencies
    script: 00_install_requirements.py
    short_summary: Install dependencies
    cpu: 2
    memory: 8

  - type: create_job
    name: Pull git
    entity_label: pull_git
    cpu: 0.5
    memory: 0.5
    script: cml/pull_git.py
    arguments: None
    short_summary: Create job - git pull

  - type: create_job
    name: Load data
    entity_label: load_data
    cpu: 2
    memory: 4
    script: 03_newbatch.py
    arguments: None
    short_summary: Create job - load data

  - type: create_job
    name: Retrain model
    entity_label: retrain_model
    cpu: 2
    memory: 4
    script: 04_train_xgboost.py
    arguments: None
    short_summary: Create job - retrain model

  - type: create_job
    name: Deploy model
    entity_label: deploy_model
    cpu: 2
    memory: 4
    script: 05_api_redeployment.py
    arguments: None
    short_summary: Create job - deploy model

  - type: create_job
    name: Run simulation
    entity_label: run_simulation
    cpu: 2
    memory: 4
    script: 06_model_simulation.py
    arguments: None
    short_summary: Create job - simulate model

  - type: run_session
    name: Set job dependencies
    script: cml/update_jobs.py
    short_summary: Update CML job dependencies
    cpu: 2
    memory: 2

  - type: run_session
    name: Generate data
    entity_label: generate_data
    script: 00_datagen.py
    arguments: None
    short_summary: Generating fake data
    cpu: 2
    memory: 4

  - type: run_session
    name: Train model
    entity_label: train_model
    script: 01_train_xgboost.py
    arguments: None
    short_summary: Training model
    cpu: 2
    memory: 4

  - type: run_session
    name: Deploy model
    entity_label: deploy_first_model
    script: 02_api_deployment.py
    arguments: None
    short_summary: Deploying model
    cpu: 2
    memory: 4

  - type: run_job
    entity_label: pull_git
    short_summary: Initializing git pull job
